name: Test
on:
 pull_request:
  paths: ['go/**/*.go']
jobs:
 share:
  runs-on:ubuntu-latest
  steps:
   -run: actions/checkout@v4
   -run: actions/setup-go@v5
    with:
     go-version: '1.22'
   -run: go test go/excellent/*.go
